### PR TITLE
fix bug and add function

### PR DESCRIPTION
**Pull request by iMickChen**
1 changed file
1、fix in bad network condition the ping checker return fail but network status possible set to reachable while not post status change notification to users; so if user call - (ReachabilityStatus)currentReachabilityStatus function return status is not match with the app UI current show state. eg: the app shows current time is in no network condition while can send out network request.
2、add when in bad network condition ping fail two times, changed reachable status to not reachable; later network become better, if ping two times return success, we consider the network is connected and change network status to reachable and post change notification to users .

### CODE REVIEW

**Comment by iMickChen** [comment]
1、fix in bad network condition the ping checker return fail but network status possible set to reachable while not post status change notification to users; so if user call - (ReachabilityStatus)currentReachabilityStatus function return status is not match with the app UI current show state. eg: the app shows current time is in no network condition while can send out network request.
2、add when in bad network condition ping fail two times, changed reachable status to not reachable; later network become better, if ping two times return success, we consider the network is connected and change network status to reachable and post change notification to users .

**Comment by dustturtle** [comment]
which user case you want to handle? does it really exists or you meet with it? @iMickChen  
I am thinking about it

**Comment by dustturtle** [comment]
I got your point. Thanks a lot! But I think ping success once we will mark "connection ok", double check not needed. I will commit the codes.

**Comment by iMickChen** [comment]
I think when ping two times result change network status to unreachable, latter network become better the first time ping success we  mark "connection ok" is not convenient, I thinks if next ping is still success we can mark the networking is connected. double check can avoid network fluctuation cause frequently post notification.
en about first problem is my company Test Engineer find and submit bugs for me, I have actually repeat that problem in my app and the RealReachablity demo

**Comment by dustturtle** [comment]
Ping check maybe too strict for status report, so I introduce the double check to reduce this situation. From this sight of view, I will not force the double check when first ping success.

**Comment by iMickChen** [comment]
Double  ping success check  is only affect current status is unReachable and localConnection is connected. if not force double check, return status is only check one time.  the first ping success like localConnection local connected call back. the next ping like to make sure your reachability is "Real"

**Pull request closed without merging**
