### PR TITLE
Carthage support

### PR DESCRIPTION
**Pull request by leoMehlig**
*Why:*
Many iOS/MacOS developer prefer `Carthage` over `CocoaPods`, because it gives them more control over what happens with their Xcode project.

*What:*
I've created a separate Xcode project with the iOS Framework template. This frameworks includes all the objc files from the `RealReachability` folder. I also set the scheme of the project to shared, this enables carthage to automatically build the framework.

*To do:*
After merging this framework can be used by added `github "dustturtle/RealReachability" "master"` to the Cartfile. Further documentation about `carthage` can be found at their [Github-Repo](https://github.com/Carthage/Carthage).
 (Right now it can be tested by adding github "leoMehlig/RealReachability" "master" to the `Cartfile`).
To be available to everyone and to work as indeed you (the owner of this repo) needs to create a new release on Github. Optionally it is probably useful to mention this in the README.md and maybe add the Carthage badge [Carthage compatible](https://github.com/Carthage/Carthage).

I hope this PR is useful to you and can be merged.

PS. As the Organisation I used `QCStudio` and as the Bundle ID `qc.RealReachability`.

### CODE REVIEW

**Comment by dustturtle** [comment]
Thank you so much！Surely your PR will be merged. Now I am in bed.^____^

**Comment by leoMehlig** [comment]
I also wanted to mention, that it might be useful to not include the framework's files directly into the test project, but rather include the framework project. But that is only my personal opinion.
If want to do this, I can open another PR.

**Comment by leoMehlig** [comment]
@dustturtle whats the status? Is it gonna be merged soon and will there be a new release which includes the carthage support?

**Comment by dustturtle** [comment]
I found that the project has the target problem. We need to support iOS6+.  So would you please modify your pull request based on the newest version with the deployment target modified? Thanks a lot! Waiting for you reply~

**Comment by leoMehlig** [comment]
@dustturtle I've set it to iOS 6!

**Pull request merged**
