### PR TITLE
Fix compile error in Xcode9-beta3

### PR DESCRIPTION
**Pull request by Daemonson**
check_compile_time had been replaced with __Check_Compile_Time in file “AssertMacros.h”

### CODE REVIEW

**Comment by umbri** [comment]
Any news about this ?

**Comment by Daemonson** [comment]
@umbri You can see the notes in the file <AssertMacros.h>. Apple notes that macOS High Sierra and iOS 11 will now require that clients move to the new macros. As follows:
/*
>  *	For time immemorial, Mac OS X has defined version of most of these macros without the __ prefix, which
>  *	could collide with similarly named functions or macros in user code, including new functionality in
>  *	Boost and the C++ standard library.
>  *
>  *  macOS High Sierra and iOS 11 will now require that clients move to the new macros as defined above.
>  *
>  *  If you would like to enable the macros for use within your own project, you can define the
>  *  __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES macro via an Xcode Build Configuration.
>  *  See "Add a build configuration (xcconfig) file" in Xcode Help. 
>  *
>  *  To aid users of these macros in converting their sources, the following tops script will convert usages
>  *  of the old macros into the new equivalents.  To do so, in Terminal go into the directory containing the
>  *  sources to be converted and run this command.
>  *
>     find . -name '*.[c|cc|cp|cpp|m|mm|h]' -print0 |  xargs -0 tops -verbose \
>       replace "check(<b args>)" with "__Check(<args>)" \
>       replace "check_noerr(<b args>)" with "__Check_noErr(<args>)" \
>       replace "check_noerr_string(<b args>)" with "__Check_noErr_String(<args>)" \
>       replace "check_string(<b args>)" with "__Check_String(<args>)" \
>       replace "require(<b args>)" with "__Require(<args>)" \
>       replace "require_action(<b args>)" with "__Require_Action(<args>)" \
>       replace "require_action_string(<b args>)" with "__Require_Action_String(<args>)" \
>       replace "require_noerr(<b args>)" with "__Require_noErr(<args>)" \
>       replace "require_noerr_action(<b args>)" with "__Require_noErr_Action(<args>)" \
>       replace "require_noerr_action_string(<b args>)" with "__Require_noErr_Action_String(<args>)" \
>       replace "require_noerr_string(<b args>)" with "__Require_noErr_String(<args>)" \
>       replace "require_string(<b args>)" with "__Require_String(<args>)" \
>       replace "verify(<b args>)" with "__Verify(<args>)" \
>       replace "verify_action(<b args>)" with "__Verify_Action(<args>)" \
>       replace "verify_noerr(<b args>)" with "__Verify_noErr(<args>)" \
>       replace "verify_noerr_action(<b args>)" with "__Verify_noErr_Action(<args>)" \
>       replace "verify_noerr_string(<b args>)" with "__Verify_noErr_String(<args>)" \
>       replace "verify_string(<b args>)" with "__Verify_String(<args>)" \
>       replace "ncheck(<b args>)" with "__nCheck(<args>)" \
>       replace "ncheck_string(<b args>)" with "__nCheck_String(<args>)" \
>       replace "nrequire(<b args>)" with "__nRequire(<args>)" \
>       replace "nrequire_action(<b args>)" with "__nRequire_Action(<args>)" \
>       replace "nrequire_action_quiet(<b args>)" with "__nRequire_Action_Quiet(<args>)" \
>       replace "nrequire_action_string(<b args>)" with "__nRequire_Action_String(<args>)" \
>       replace "nrequire_quiet(<b args>)" with "__nRequire_Quiet(<args>)" \
>       replace "nrequire_string(<b args>)" with "__nRequire_String(<args>)" \
>       replace "nverify(<b args>)" with "__nVerify(<args>)" \
>       replace "nverify_string(<b args>)" with "__nVerify_String(<args>)" \
>       replace "require_action_quiet(<b args>)" with "__Require_Action_Quiet(<args>)" \
>       replace "require_noerr_action_quiet(<b args>)" with "__Require_noErr_Action_Quiet(<args>)" \
>       replace "require_noerr_quiet(<b args>)" with "__Require_noErr_Quiet(<args>)" \
>       replace "require_quiet(<b args>)" with "__Require_Quiet(<args>)" \
>       replace "check_compile_time(<b args>)" with "__Check_Compile_Time(<args>)" \
>       replace "debug_string(<b args>)" with "__Debug_String(<args>)"
>  *
>  */

**Comment by dustturtle** [comment]
Could you please confirm the new checking worked in old versions, such as xcode 7 iOS7?

**Comment by dustturtle** [comment]
@Daemonson

**Comment by Daemonson** [comment]
@dustturtle Yes, I just now tested the code with Xcode7.2 and iPhone 5C(iOS7.1.2), all goes well.
image
image

**Comment by dustturtle** [comment]
Thanks a lot for your great efforts!

**Pull request merged**
